
# SQL QUERIES FOR CREATE NECESSARY TABLES

create_users_table = """
CREATE TABLE USERS(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT,
   DESCR        CHAR(50)
);
"""

create_memes_table = """
CREATE TABLE memes(
   ID SERIAL PRIMARY KEY,
   TG_ID INT UNIQUE NOT NULL,
   AUTHOR_ID    INT   NOT NULL,
   CREATE_DATE TIMESTAMP,
   CONSTRAINT meme_author
      FOREIGN KEY(AUTHOR_ID)
        REFERENCES USERS(ID)
);
"""

create_users_users_table = """
CREATE TABLE users_users(
   ID  SERIAL PRIMARY KEY,
   USER_ID INT NOT NULL,
   REC_USER_ID    INT   NOT NULL,
   REACTION BOOLEAN NOT NULL,
   DATE TIMESTAMP,
   CONSTRAINT act_user
      FOREIGN KEY(USER_ID)
        REFERENCES USERS(ID),
   CONSTRAINT rec_user
      FOREIGN KEY(REC_USER_ID)
        REFERENCES USERS(ID)
);
"""

create_users_memes_table = """
CREATE TABLE users_memes(
   ID  SERIAL PRIMARY KEY,
   USER_ID INT NOT NULL,
   MEMES_ID INT NOT NULL,
   REACTION INT NOT NULL,
   DATE TIMESTAMP,
   CONSTRAINT user_const
      FOREIGN KEY(USER_ID)
        REFERENCES USERS(ID),
   CONSTRAINT meme_const
      FOREIGN KEY(MEMES_ID)
        REFERENCES MEMES(ID)
);
"""
